version: 2.1

jobs:
  build:
#     working_directory: ~/circleci-python
#     docker:
#       - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: npm test
  test:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: npm test

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
